USE [master]
GO
/****** Object:  Database [VOTACAO]    Script Date: 30/11/2022 21:28:44 ******/
CREATE DATABASE [VOTACAO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VOTACAO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VOTACAO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VOTACAO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VOTACAO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [VOTACAO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VOTACAO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VOTACAO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VOTACAO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VOTACAO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VOTACAO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VOTACAO] SET ARITHABORT OFF 
GO
ALTER DATABASE [VOTACAO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VOTACAO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VOTACAO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VOTACAO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VOTACAO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VOTACAO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VOTACAO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VOTACAO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VOTACAO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VOTACAO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VOTACAO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VOTACAO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VOTACAO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VOTACAO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VOTACAO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VOTACAO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VOTACAO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VOTACAO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [VOTACAO] SET  MULTI_USER 
GO
ALTER DATABASE [VOTACAO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VOTACAO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VOTACAO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VOTACAO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VOTACAO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [VOTACAO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [VOTACAO] SET QUERY_STORE = OFF
GO
USE [VOTACAO]
GO
/****** Object:  Schema [acesso]    Script Date: 30/11/2022 21:28:44 ******/
CREATE SCHEMA [acesso]
GO
/****** Object:  Schema [eleicao]    Script Date: 30/11/2022 21:28:44 ******/
CREATE SCHEMA [eleicao]
GO
/****** Object:  Table [acesso].[TB_PERMISSAO]    Script Date: 30/11/2022 21:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [acesso].[TB_PERMISSAO](
	[ID_PERMISSAO] [uniqueidentifier] NOT NULL,
	[NM_CLAIM] [varchar](255) NOT NULL,
	[CLAIM_VALUE] [varchar](255) NOT NULL,
 CONSTRAINT [DF_TB_PERMISSAO] PRIMARY KEY CLUSTERED 
(
	[ID_PERMISSAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [acesso].[TB_TIPO_USUARIO]    Script Date: 30/11/2022 21:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [acesso].[TB_TIPO_USUARIO](
	[ID_TIPO_USUARIO] [uniqueidentifier] NOT NULL,
	[NM_TIPO_USUARIO] [varchar](255) NOT NULL,
 CONSTRAINT [PK_TB_TIPO_USUARIO] PRIMARY KEY NONCLUSTERED 
(
	[ID_TIPO_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [acesso].[TB_TIPO_USUARIO_PERMISSAO]    Script Date: 30/11/2022 21:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [acesso].[TB_TIPO_USUARIO_PERMISSAO](
	[ID_TIPO_USUARIO_PERMISSAO] [uniqueidentifier] NOT NULL,
	[ID_TIPO_USUARIO] [uniqueidentifier] NOT NULL,
	[ID_PERMISSAO] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [acesso].[TB_USUARIO]    Script Date: 30/11/2022 21:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [acesso].[TB_USUARIO](
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[NM_USUARIO] [varchar](255) NOT NULL,
	[NR_CPF] [varchar](11) NOT NULL,
	[SENHA] [varchar](255) NOT NULL,
	[ID_TIPO_USUARIO] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_TB_USUARIO] PRIMARY KEY NONCLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [acesso].[TB_USUARIO_PERMISSAO]    Script Date: 30/11/2022 21:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [acesso].[TB_USUARIO_PERMISSAO](
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[ID_PERMISSAO] [uniqueidentifier] NOT NULL,
	[ID_USUARIO_PERMISSAO] [uniqueidentifier] NOT NULL,
 CONSTRAINT [DF_TB_USUARIO_PERMISSAO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO_PERMISSAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [eleicao].[TB_ELEICAO]    Script Date: 30/11/2022 21:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [eleicao].[TB_ELEICAO](
	[ID_ELEICAO] [uniqueidentifier] NOT NULL,
	[NM_ELEICAO] [varchar](255) NOT NULL,
	[DT_INICO_ELEICAO] [datetime] NOT NULL,
	[DT_TERMINO_ELEICAO] [datetime] NOT NULL,
 CONSTRAINT [PK_TB_ELEICAO] PRIMARY KEY NONCLUSTERED 
(
	[ID_ELEICAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [eleicao].[TB_ELEICAO_CANDIDATO]    Script Date: 30/11/2022 21:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [eleicao].[TB_ELEICAO_CANDIDATO](
	[ID_ELEICAO_CANDIDATO] [uniqueidentifier] NOT NULL,
	[ID_ELEICAO] [uniqueidentifier] NOT NULL,
	[ID_CANDIDATO] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_TB_ELEICAO_CANDIDATO] PRIMARY KEY NONCLUSTERED 
(
	[ID_ELEICAO_CANDIDATO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [eleicao].[TB_VOTO]    Script Date: 30/11/2022 21:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [eleicao].[TB_VOTO](
	[ID_VOTO] [uniqueidentifier] NOT NULL,
	[ID_ELEICAO_CANDIDATO] [uniqueidentifier] NOT NULL,
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_TB_VOTO_ID_VOTO] PRIMARY KEY NONCLUSTERED 
(
	[ID_VOTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [acesso].[TB_PERMISSAO] ADD  CONSTRAINT [DF_TB_PERMISSAO_ID_PERMISSAO]  DEFAULT (newsequentialid()) FOR [ID_PERMISSAO]
GO
ALTER TABLE [acesso].[TB_TIPO_USUARIO] ADD  CONSTRAINT [DF_TB_TIPO_USUARIO_ID_TIPO_USUARIO]  DEFAULT (newsequentialid()) FOR [ID_TIPO_USUARIO]
GO
ALTER TABLE [acesso].[TB_TIPO_USUARIO_PERMISSAO] ADD  CONSTRAINT [DF_TB_TIPO_USUARIO_PERMISSAO]  DEFAULT (newsequentialid()) FOR [ID_TIPO_USUARIO_PERMISSAO]
GO
ALTER TABLE [acesso].[TB_USUARIO] ADD  CONSTRAINT [DF_TB_USUARIO_ID_USUARIO]  DEFAULT (newsequentialid()) FOR [ID_USUARIO]
GO
ALTER TABLE [acesso].[TB_USUARIO_PERMISSAO] ADD  CONSTRAINT [DF_TB_USUARIO_PERMISSAO_ID_PERMISSAO]  DEFAULT (newsequentialid()) FOR [ID_USUARIO_PERMISSAO]
GO
ALTER TABLE [eleicao].[TB_ELEICAO] ADD  CONSTRAINT [DF_TB_ELEICAO_ID_ELEICAO]  DEFAULT (newsequentialid()) FOR [ID_ELEICAO]
GO
ALTER TABLE [eleicao].[TB_ELEICAO_CANDIDATO] ADD  CONSTRAINT [DF_TB_ELEICAO_CANDIDATO_ID_ELEICAO_CANDIDATO]  DEFAULT (newsequentialid()) FOR [ID_ELEICAO_CANDIDATO]
GO
ALTER TABLE [eleicao].[TB_VOTO] ADD  CONSTRAINT [DF_TB_VOTO_ID_VOTO]  DEFAULT (newsequentialid()) FOR [ID_VOTO]
GO
ALTER TABLE [acesso].[TB_TIPO_USUARIO_PERMISSAO]  WITH CHECK ADD  CONSTRAINT [FK_TB_TIPO_USUARIO_PERMISSAO_ID_PERMISSAO] FOREIGN KEY([ID_PERMISSAO])
REFERENCES [acesso].[TB_PERMISSAO] ([ID_PERMISSAO])
GO
ALTER TABLE [acesso].[TB_TIPO_USUARIO_PERMISSAO] CHECK CONSTRAINT [FK_TB_TIPO_USUARIO_PERMISSAO_ID_PERMISSAO]
GO
ALTER TABLE [acesso].[TB_TIPO_USUARIO_PERMISSAO]  WITH CHECK ADD  CONSTRAINT [FK_TB_TIPO_USUARIO_PERMISSAO_ID_TIPO_USUARIO] FOREIGN KEY([ID_TIPO_USUARIO])
REFERENCES [acesso].[TB_TIPO_USUARIO] ([ID_TIPO_USUARIO])
GO
ALTER TABLE [acesso].[TB_TIPO_USUARIO_PERMISSAO] CHECK CONSTRAINT [FK_TB_TIPO_USUARIO_PERMISSAO_ID_TIPO_USUARIO]
GO
ALTER TABLE [acesso].[TB_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TB_USUARIO_ID_TIPO_USUARIO] FOREIGN KEY([ID_TIPO_USUARIO])
REFERENCES [acesso].[TB_TIPO_USUARIO] ([ID_TIPO_USUARIO])
GO
ALTER TABLE [acesso].[TB_USUARIO] CHECK CONSTRAINT [FK_TB_USUARIO_ID_TIPO_USUARIO]
GO
ALTER TABLE [acesso].[TB_USUARIO_PERMISSAO]  WITH CHECK ADD  CONSTRAINT [FK_TB_USUARIO_PERMISSAO_ID_PERMISSAO] FOREIGN KEY([ID_PERMISSAO])
REFERENCES [acesso].[TB_PERMISSAO] ([ID_PERMISSAO])
GO
ALTER TABLE [acesso].[TB_USUARIO_PERMISSAO] CHECK CONSTRAINT [FK_TB_USUARIO_PERMISSAO_ID_PERMISSAO]
GO
ALTER TABLE [acesso].[TB_USUARIO_PERMISSAO]  WITH CHECK ADD  CONSTRAINT [FK_TB_USUARIO_PERMISSAO_ID_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [acesso].[TB_USUARIO] ([ID_USUARIO])
GO
ALTER TABLE [acesso].[TB_USUARIO_PERMISSAO] CHECK CONSTRAINT [FK_TB_USUARIO_PERMISSAO_ID_USUARIO]
GO
ALTER TABLE [eleicao].[TB_ELEICAO_CANDIDATO]  WITH CHECK ADD  CONSTRAINT [FK_TB_ELEICAO_CANDIDATO_ID_CANDIDATO] FOREIGN KEY([ID_CANDIDATO])
REFERENCES [acesso].[TB_USUARIO] ([ID_USUARIO])
GO
ALTER TABLE [eleicao].[TB_ELEICAO_CANDIDATO] CHECK CONSTRAINT [FK_TB_ELEICAO_CANDIDATO_ID_CANDIDATO]
GO
ALTER TABLE [eleicao].[TB_ELEICAO_CANDIDATO]  WITH CHECK ADD  CONSTRAINT [FK_TB_ELEICAO_CANDIDATO_ID_ELEICAO] FOREIGN KEY([ID_ELEICAO])
REFERENCES [eleicao].[TB_ELEICAO] ([ID_ELEICAO])
GO
ALTER TABLE [eleicao].[TB_ELEICAO_CANDIDATO] CHECK CONSTRAINT [FK_TB_ELEICAO_CANDIDATO_ID_ELEICAO]
GO
ALTER TABLE [eleicao].[TB_VOTO]  WITH CHECK ADD  CONSTRAINT [FK_TB_VOTO_ID_ELEICAO_CANDIDATO] FOREIGN KEY([ID_ELEICAO_CANDIDATO])
REFERENCES [eleicao].[TB_ELEICAO_CANDIDATO] ([ID_ELEICAO_CANDIDATO])
GO
ALTER TABLE [eleicao].[TB_VOTO] CHECK CONSTRAINT [FK_TB_VOTO_ID_ELEICAO_CANDIDATO]
GO
ALTER TABLE [eleicao].[TB_VOTO]  WITH CHECK ADD  CONSTRAINT [FK_TB_VOTO_ID_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [acesso].[TB_USUARIO] ([ID_USUARIO])
GO
ALTER TABLE [eleicao].[TB_VOTO] CHECK CONSTRAINT [FK_TB_VOTO_ID_USUARIO]
GO
USE [master]
GO
ALTER DATABASE [VOTACAO] SET  READ_WRITE 
GO
