create schema acesso
create schema eleicao

create table acesso.TB_TIPO_USUARIO(
	ID_TIPO_USUARIO UNIQUEIDENTIFIER CONSTRAINT [DF_TB_TIPO_USUARIO_ID_TIPO_USUARIO] DEFAULT (newsequentialid()) NOT NULL,
	NM_TIPO_USUARIO varchar(255) not null,
	CONSTRAINT [PK_TB_TIPO_USUARIO] PRIMARY KEY NonCLUSTERED (ID_TIPO_USUARIO),
)


create table acesso.TB_USUARIO(
	ID_USUARIO UNIQUEIDENTIFIER CONSTRAINT [DF_TB_USUARIO_ID_USUARIO] DEFAULT (newsequentialid()) NOT NULL,
	NM_USUARIO varchar(255) not null,
	NR_CPF varchar(11) not null,
	SENHA varchar(255) not null,
	CONSTRAINT [PK_TB_USUARIO] PRIMARY KEY NonCLUSTERED (ID_USUARIO),
	ID_TIPO_USUARIO UNIQUEIDENTIFIER not null constraint FK_TB_USUARIO_ID_TIPO_USUARIO references acesso.TB_TIPO_USUARIO(ID_TIPO_USUARIO)
)
go

create table eleicao.TB_ELEICAO(
	ID_ELEICAO UNIQUEIDENTIFIER CONSTRAINT [DF_TB_ELEICAO_ID_ELEICAO] DEFAULT (newsequentialid()) NOT NULL, 
	NM_ELEICAO VARCHAR(255) not null,
	DT_INICO_ELEICAO DATETIME not null,
	DT_TERMINO_ELEICAO DATETIME NOT NULL,
		CONSTRAINT [PK_TB_ELEICAO] PRIMARY KEY NonCLUSTERED (ID_ELEICAO),
)
go
create table eleicao.TB_ELEICAO_CANDIDATO(
	ID_ELEICAO_CANDIDATO UNIQUEIDENTIFIER CONSTRAINT [DF_TB_ELEICAO_CANDIDATO_ID_ELEICAO_CANDIDATO] DEFAULT (newsequentialid()) NOT NULL, 
	ID_ELEICAO UNIQUEIDENTIFIER not null constraint FK_TB_ELEICAO_CANDIDATO_ID_ELEICAO references eleicao.TB_ELEICAO(ID_ELEICAO),
	ID_CANDIDATO UNIQUEIDENTIFIER not null constraint FK_TB_ELEICAO_CANDIDATO_ID_CANDIDATO references acesso.TB_USUARIO(ID_USUARIO)
	CONSTRAINT [PK_TB_ELEICAO_CANDIDATO] PRIMARY KEY NonCLUSTERED (ID_ELEICAO_CANDIDATO),
)
go
create table eleicao.TB_VOTO(
	ID_VOTO UNIQUEIDENTIFIER CONSTRAINT [DF_TB_VOTO_ID_VOTO] DEFAULT (newsequentialid()) NOT NULL, 
	ID_ELEICAO_CANDIDATO UNIQUEIDENTIFIER not null constraint FK_TB_VOTO_ID_ELEICAO_CANDIDATO references eleicao.TB_ELEICAO_CANDIDATO(ID_ELEICAO_CANDIDATO),
	ID_USUARIO UNIQUEIDENTIFIER not null constraint FK_TB_VOTO_ID_USUARIO references acesso.TB_USUARIO(ID_USUARIO)
	CONSTRAINT [PK_TB_VOTO_ID_VOTO] PRIMARY KEY NonCLUSTERED (ID_VOTO),
)

