USE [master]
GO

/****** Object:  Database [VOTACAO]    Script Date: 29/11/2022 22:12:34 ******/
CREATE DATABASE [VOTACAO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VOTACAO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VOTACAO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VOTACAO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VOTACAO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VOTACAO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VOTACAO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VOTACAO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VOTACAO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VOTACAO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VOTACAO] SET ARITHABORT OFF 
GO

ALTER DATABASE [VOTACAO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VOTACAO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VOTACAO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VOTACAO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VOTACAO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VOTACAO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VOTACAO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VOTACAO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VOTACAO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VOTACAO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VOTACAO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VOTACAO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VOTACAO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VOTACAO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VOTACAO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VOTACAO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VOTACAO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VOTACAO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [VOTACAO] SET  MULTI_USER 
GO

ALTER DATABASE [VOTACAO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VOTACAO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VOTACAO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VOTACAO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VOTACAO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VOTACAO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [VOTACAO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [VOTACAO] SET  READ_WRITE 
GO


